apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: platform-demo-role
  namespace: platform-demo
rules:
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: platform-demo-rolebinding
  namespace: platform-demo
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: platform-demo-role
subjects:
- kind: ServiceAccount
  name: default
  namespace: platform-demo
